### PR TITLE
Update to latest util lib

### PR DESCRIPTION
**Pull request by pirgeo**
Also updated the GH action to only test active go versions and test all OSes

### CODE REVIEW

**Review by joaopgrassi — APPROVED** [review]

**Review by joaopgrassi — COMMENTED** [review]
I guess we have the same situation here right? We require go 1.15 but build in others. Not sure what updating entails for consumers but maybe we should do that?

**Comment by pirgeo** [comment]
I am not sure if we need a new release of the util lib, we updated just the versions of go we are testing here: https://github.com/dynatrace-oss/dynatrace-metric-utils-go/pull/15. @dyladan WDYT, should we release a 0.4.1 with the updated go versions? I am not too familiar how this is usually done in go...

We also raised the go version that the library is compatible with, so maybe we should release that change.

**Review by joaopgrassi — APPROVED** [review]

**Comment by joaopgrassi** [comment]
I guess if it was just updating the go required go version we shouldn't bother with a new release, but since we also updated the `utils` version I believe a new version is necessary.

**Review by dyladan — APPROVED** [review]

**Comment by dyladan** [comment]
The version in the go.mod can be thought of as the minimum version. Requiring dependencies which have a lower minimum should not be a problem, but requiring dependencies with a higher minimum can cause issues if you're not using an updated go compiler. In this case I think it's fine for the utils library to be 1.15 when this is 1.17 but it should probably be updated just to be consistent eventually. AFAIK we don't have an established policy for deprecating old runtime versions in any of our exporters.

**Comment by pirgeo** [comment]
I released a new version (https://github.com/dynatrace-oss/dynatrace-metric-utils-go/releases/tag/v0.5.0) and bumped the version here, just so we don't forget.

**Review by joaopgrassi — APPROVED** [review]

**Pull request merged**
